logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
    web: DEBUG
server:
  port: 8086
spring:
  application:
    name: userprofile-mongo-service
  data:
    mongodb:
      database: userprofile
      uri: mongodb://localhost:27017/userprofile