logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
    web: DEBUG
server:
  port: 8086
spring:
  application:
    name: userprofile-mongo-service
  data:
    mongodb:
      database: userprofile
      uri: mongodb://ec2-43-205-195-15.ap-south-1.compute.amazonaws.com:27017/userprofile